version: 2

sources: # Separated
  - name: public
    description: 'A source for get data from public schema'
    database: postgres
    schema: public
    tables:
      - name: most_listened_songs
  - name: duplicate
    description: 'A source for get data from duplicate schema'
    database: postgres
    schema: duplicate
    tables:
      - name: most_listened_songs

models:
  - name: most_listened_songs
  #   columns:
  #     - name: ids
  #       tests:
  #         - unique
  #         - not_null
  # - name: most_listened_songs
  #   columns:
  #     - name: title
  #       tests:
  #         - not_null
  # - name: most_listened_songs
  #   columns:
  #     - name: artist
  #       tests:
  #         - not_null
  # - name: most_listened_songs
  #   columns:
  #     - name: genre
  #       tests:
  #         - not_null